// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/env': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/env.get').default>>>>
    }
    '/healthz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/healthz.get').default>>>>
    }
    '/readyz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/readyz.get').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/robots.txt').default>>>>
    }
    '/rss.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/rss.xml').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/sitemap.xml').default>>>>
    }
    '/sw.js': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/sw.js').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}